<section id="sobre">
    <div class ="container">
    <h2 class="subtitle">Sobre o Evento</h2>
    <p>O grupo de usu&aacute;rios de Software Livre Tchelinux, em parceria
    com {cursos} <a href="{institution[url]}">{institution[long_name]}</a>,
    tem o prazer de convidar a comunidade para participar do evento que
    ocorrer&aacute; no dia <b>{date_str}</b> a partir das 8:30h na
    {institution[short_name]} em {city}.</p>
    <p><a href="codigo_de_conduta.html" target="_top"><b>C&oacute;digo
    de Conduta do Tchelinux.</b></a></p>
</section>
