<section id="sobre">
    <div class ="container">
    <h2 class="subtitle">Sobre o Evento</h2>
    <p>O grupo de usu&aacute;rios de Software Livre Tchelinux, em parceria com
        {instituicao[artigo]}
        {instituicao[diretorio]}
        <a href="{instituicao[url]}">{instituicao[long_name]}</a>,
        tem o prazer de convidar a comunidade, independente do n&iacute;vel
        de conhecimento e experi&ecirc;ncia com tecnologia, software livre e
        &aacute;reas afins, para participar do evento que ocorrer&aacute; no dia
        <b>{data}</b> a partir das 8:30h na {instituicao[short_name]}
        em {cidade}.</p>
    <p><a href="/codigo_de_conduta.html" target="_top"><b>C&oacute;digo de Conduta do Tchelinux.</b></a></p>
</section>
