<section id="sobre">
    <div class ="container">
    <h2 class="subtitle">Sobre o Evento</h2>
    <p>O grupo de usuários de Software Livre Tchelinux, em parceria com
        {instituicao[artigo]}
        {instituicao[diretorio]}
        <a href="{instituicao[url]}">{instituicao[long_name]}</a>,
        tem o prazer de convidar a comunidade, independente do nível
        de conhecimento e experiência com tecnologia, software livre e
        áreas afins, para participar do evento que ocorrerá no dia
        <b>{data}</b> a partir das 8:30h na {instituicao[short_name]}
        em {cidade}.</p>
    <p><a href="codigo_de_conduta.html" target="_top"><b>Código de Conduta do Tchelinux.</b></a></p>
</section>
