<div id="speech-{count}" class=speech-container>
    <span class="speech-time" style="text-align:center;">{time}<br/>
        <span style="font-size:smaller;">Sala</span><br/>
        <span style="font-size:smaller;">{number}</span>
    </span>
    <div class="speech-info">
    <h3 class="speech-title">
        {title}
    <!-- TODO: generate liks for SLIDES and CODE
    <a href="#">
        <span class="label label-default slides">SLIDES</span>
    </a>
    -->
    </h3>
    <span class="speech-description">{abstract}</span>
    <h3 class="speaker-name">{author}</h3>
    <span class="speaker-bio">{resume}</span>
</div>
