<section id="programacao">
    <div class="container">
        <h2 class="subtitle">Programação</h2>
        <p>O evento está com a chamada de trabalhos aberta. Assim que a
        programação começar a ser definida, será divulgada nesse espaço.
        </p>
    </div>
</section>

<section id="call4papers">
    <div class="container">
        <h2 class="subtitle">Chamada de Trabalhos</h2>
        <p>A Chamada de Trabalhos para o Tchelinux {city} está aberta e
        caso você tenha interesse em submeter uma palestra, por favor,
        preencha o <a target="_blank" href="{callForPapers[url]}">
        formulário de submissão de palestras</a>.</p>
        <p>O prazo máximo para submissão é
        <b>{callForPapers[deadline_str]}</b>, e os trabalhos escolhidos
        serão publicados no dia <b>{callForPapers[notice_str]}.</b></p>
        <p><a target="_blank" href="{callForPapers[url]}">Clique aqui e
        submeta sua Palestra agora mesmo!</a></p>
    </div>
</section>
