<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="list-inline" id="footer-menu">
                    <li class="active"><a href="#">Tchelinux</a></li>
                    <li><a href="#inscricao">{titulo_inscricoes}</a></li>
                    <li><a href="#certificados">Certificados</a></li>
                    <li><a href="#programacao">Programa&ccedil;&atilde;o</a></li>
                    <li><a href="#palestras">Palestras</a></li>
                    <li><a href="#local">Local</a></li>
                    <li><a href="#apoio">Apoio</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
