<head>
    <base target="_blank">
    <title>Tchelinux Santa Cruz - 2017</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
    <!-- OpenGraph -->
    <meta property="og:image" content="https://tchelinux.org/assets/tchelinux-facebook.png">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <!-- Google Maps -->
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
    <!--Bootstrap -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <!-- Tchelinux Style -->
    <link rel="stylesheet" type="text/css" href="css/style.css">
</head>
