<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Tchelinux</a>
        </div>
        <div class="collapse navbar-collapse" id="main-navbar">
            <ul class="nav navbar-nav">
                <li style="display:none;"><a href="#sobre">Sobre</a></li>
                <li><a href="#inscricao">{titulo_inscricoes}</a></li>
                <li><a href="#certificados">Certificados</a></li>
                <li><a href="#programacao">Programação</a></li>
                <li><a href="#palestras">Palestras</a></li>
                <li><a href="#local">Local</a></li>
                <li><a href="#apoio">Apoio</a></li>
            </ul>
        </div>
    </div>
</nav>
