<section id="apoio">
    <div class="container">
        <div id="apoio_evento">
            <h2 class="subtitle">Apoio</h2>
            {sponsor_list}
            <h4>Institucional</h4>
            <ul class="apoio-list">
                <li class="apoio-item">
                    <a href="{institution[url]}" title="Institui&ccedil;&atilde;o" class="apoio-logo apoio-link">
                    <img src="images/{institution[logo]}" alt="{institution[short_name]}" class="photo"/>
                    </a>
                </li>
                {support_list}
            </ul>
            <h4>Gostaria de patrocinar os eventos do Tchelinux?</h4>
            <ul class="apoio-list">
                <li class="apoio-item">
                    <a href="https://goo.gl/eLSqYm" title="Seja um patrocinador" class="apoio-logo apoio-link">
                    <span class="glyphicon glyphicon-plus"></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</section>
