<section id="apoio">
    <div class="container">
        <div id="apoio_evento">
            <h2 class="subtitle">Apoio</h2>
            <h4>Institucional</h4>
            <ul class="apoio-list">
                <li class="apoio-item">
                    <a href="{instituicao[url]}" title="Instituição" class="apoio-logo apoio-link">
                    <img src="{instituicao[logo]}" alt="{instituicao[short_name]}" class="photo"/>
                    </a>
                </li>
            </ul>
        </div>
        <div id="patrocinio_evento">
            <!-- <h4>Patrocinio</h4> list de patrocinadores-->
            <h4>Gostaria de Patrocinar os eventos do Tchelinux?</h4>
            <ul class="apoio-list">
                <li class="apoio-item">
                    <a href="https://goo.gl/eLSqYm" title="Seja um patrocinador" class="apoio-logo apoio-link">
                    <span class="glyphicon glyphicon-plus"></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</section>
